
service_config:
  service_address: https://api.siliconflow.cn # http://0.0.0.0:9911
  route: /supernode/bizyair-sdxl-comfy-ksampler
  service_route: "{{ service_config.service_address }}{{ service_config.route }}"

server_format:
  BizyAir_KSampler: KSampler
  
# class_types:
#   CheckpointLoaderSimple:
#     max_instances: 1
#     node_ids: [0]
#     inputs:
#       ckpt_name:
#         - sdxl/Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors
#   ControlNetLoader:
#     max_instances: 1
#     node_ids: [1]
#     inputs:
#       control_net_name:
#         - sdxl/diffusion_pytorch_model_promax.safetensors
#   ControlNetApply:
#     max_instances: 1
#     node_ids: [2]
#   CLIPTextEncode:
#     max_instances: 2
#     node_ids: [3, 4]
#   VAEDecode:
#     max_instances: 1
#     node_ids: [5]
#   VAEEncode:
#     max_instances: 1
#     node_ids: [6]
#   VAEEncodeForInpaint:
#     max_instances: 1
#     node_ids: [7]
#   LoraLoader:
#     max_instances: 2
#     node_ids: [8,9]
#     inputs:
#       lora_name:
#         - sdxl/watercolor_v1_sdxl_lora.safetensors
#         - sdxl/Cute_Animals.safetensors
#   KSampler:
#     max_instances: 1
#     node_ids: [10]
#     steps: [1, 30]
#   IPAdapterUnifiedLoader:
#     max_instances: 1
#     node_ids: [11]
#     inputs:
#       preset:
#         - "PLUS (high strength)"
#   IPAdapter:
#     max_instances: 1
#     node_ids: [12]
#   IPAdapterAdvanced:
#     max_instances: 1
#     node_ids: [13]
#   CLIPVisionLoader:
#     max_instances: 1
#     node_ids: [14]
#   IPAdapterStyleComposition:
#     max_instances: 1
#     node_ids: [15]
#   ComfyAirLoadData:
#     max_instances: 10
#     inputs:
#       max_height: 1536
#       max_width: 1536
